name: timber
description: A starting point for Dart libraries or applications.
version: 1.0.0+1
homepage: https://github.com/dietfriends/timber.dart/tree/main/timber
repository: https://github.com/dietfriends/timber.dart/

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  logging: ^1.0.1
  quiver: ^3.0.1
  synchronized: ^3.0.0
  meta: ^1.3.0
  async: ^2.5.0

dev_dependencies:
  pedantic: ^1.11.0
  mocktail: ^0.1.2
  flutter_test:
    sdk: flutter
