name: timber
description: A starting point for Dart libraries or applications.
version: 0.1.0
homepage: https://github.com/dietfriends/timber.dart

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  logging: any
  quiver:
  synchronized:

dev_dependencies:
  pedantic: ^1.9.0
  flutter_test:
    sdk: flutter
