name: timber_sentry
description: Timber Tree implementation for Sentry.
version: 0.0.2+1
homepage: https://github.com/dietfriends/timber.dart/tree/main/timber_sentry
repository: https://github.com/dietfriends/timber.dart/

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  timber: ^0.3.0
  time_machine: '>=0.9.0 <1.0.0'
  quiver: '>=2.0.0 <3.0.0'
  pedantic: '>=1.0.0 <2.0.0'
  sentry: ^4.0.0-alpha.1
  package_info: '>=0.4.0 <1.0.0'
  device_info: ^1.0.0
  battery: ^1.0.7
  logging: ^0.11.0
  async: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: any
  flutter_driver:
    sdk: flutter