name: timber_sentry
description: A new Flutter project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  timber:
    path:
      ../timber
  time_machine: '<1.0.0'
  quiver: '>=2.0.0 <3.0.0'
  pedantic: '>=1.0.0 <2.0.0'
  sentry: ^4.0.0-alpha.1
  package_info: '<1.0.0'
  device_info: ^1.0.0
  battery: ^1.0.7

  async: ^2.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: any