name: timber_crashlytics
description: Timber Tree implementation for Firebase Crashlytics.
version: 0.0.1
homepage: https://github.com/dietfriends/timber.dart/tree/main/timber_crashlytics
repository: https://github.com/dietfriends/timber.dart/

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  timber: '^0.3.0'
  firebase_crashlytics: ^0.2.0
  logging: ^0.11.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.5.1
  firebase_core: ^0.5.2
  stack_trace: ^1.9.6
  firebase_core_platform_interface: ^2.0.0
  firebase_crashlytics_platform_interface: ^1.1.3

flutter:
