name: timber_mixpanel
description: Timber Tree implementation for Mixpanel.
version: 0.0.1
homepage: https://github.com/dietfriends/timber.dart/tree/main/timber_mixpanel
repository: https://github.com/dietfriends/timber.dart/

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_mixpanel: ^0.2.0+3
  time_machine: '>=0.9.0 <1.0.0'
  quiver: '>=2.0.0 <3.0.0'
  pedantic: '>=1.0.0 <2.0.0'
  logging: ^0.11.0
  timber: ^0.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: any