name: timber_mixpanel
description: Timber Tree implementation for Mixpanel.
version: 1.0.0+1
homepage: https://github.com/dietfriends/timber.dart/tree/main/timber_mixpanel
repository: https://github.com/dietfriends/timber.dart/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_mixpanel: ^0.5.0-1.0.nullsafety.1
  #time_machine: '>=0.9.0 <1.0.0'
  quiver: ^3.0.1
  pedantic: ^1.11.0
  logging: ^1.0.1
  timber: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^0.1.2