name: timber_mixpanel
description: Timber Tree implementation for Mixpanel.
version: 2.0.0
homepage: https://github.com/dietfriends/timber.dart/tree/main/timber_mixpanel
repository: https://github.com/dietfriends/timber.dart/

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"
dependencies:
  flutter:
    sdk: flutter
  mixpanel_flutter: ^1.4.5
  quiver: ^3.0.1
  logging: ^1.0.1
  timber: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  mocktail: ^0.1.2