name: Test and coverage

on:
  push:
    branches:
      - main

  pull_request:
    paths:
      - 'package/**'

jobs:
  title:
    name: package test
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        package: [ "timber", "timber_crashlytics", "timber_firebase_analytics", "timber_mixpanel", "timber_sentry" ]
        version: [ "1.22.3" ]

    steps:
      - uses: actions/checkout@v2
      - name: Cache Flutter
        id: cache-flutter
        uses: actions/cache@v2
        with:
          path: /opt/hostedtoolcache/flutter
          key: ${{ runner.os }}-flutter-install-cache-${{ matrix.version }}

      - uses: subosito/flutter-action@v1
        with:
          flutter-version: ${{ matrix.version }}
      - uses: stelynx/dart-full-coverage@master
        with:
          use_git_root: false
          main_dir: ${{ matrix.package }}
          package: ${{ matrix.package }}
      - name: Install dependencies
        working-directory: ${{ matrix.package }}
        run: |
          flutter pub get
          flutter pub global activate remove_from_coverage
          flutter pub global activate junitreport
      - name: Run tests
        working-directory: ${{ matrix.package }}
        run: |
          flutter test --coverage --machine > machine.jsonl
          flutter pub global run junitreport:tojunit --input machine.jsonl --output TEST-report.xml
          flutter pub global run remove_from_coverage -f coverage/lcov.info -r '.freezed.dart$'
      #- name: Publish Test Report
      #  uses: mikepenz/action-junit-report@v1
      #  with:
      #    report_paths: ${{ matrix.package }}/TEST-report.xml
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload coverage to codecov
        uses: codecov/codecov-action@v1
        if: ${{ matrix.version == '1.22.3' }}
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          flags: ${{ matrix.package }}
          file: ./${{ matrix.package }}/coverage/lcov.info